name: CI

on:
  push:
    branches:
    tags:
  pull_request:



jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
        env: ['EXECUTOR= DEPENDENCIES=--prefer-lowest', 'EXECUTOR=coroutine DEPENDENCIES=--prefer-lowest', 'EXECUTOR=', 'EXECUTOR=coroutine']
    steps:
    - uses: actions/checkout@v1
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php  }}
        extension-csv: dom
        coverage: xdebug
    - name: Show php version
      run: php${{ matrix.php }} -v && composer -V
    - name: Install dependencies
      run: |
        echo $ENV
        ENV composer update --prefer-dist
      env:
        ENV: $ {{ matrix.env }}
    - name: Run unit tests
      run: |
        ENV ./vendor/bin/phpunit --group default,ReactPromise
      env:
        ENV: $ {{ matrix.env}}
    - name: Run style-fixer
      run: php${{ matrix.php }} vendor/bin/php-cs-fixer fix --dry-run
    - name: Code coverage
      run: |
        ./vendor/bin/phpunit --coverage-php /tmp/coverage/clover_executor.cov
        EXECUTOR=coroutine ./vendor/bin/phpunit --coverage-php /tmp/coverage/clover_executor-coroutine.cov
        ./vendor/bin/phpcov merge /tmp/coverage --clover /tmp/clover.xml
        wget https://github.com/scrutinizer-ci/ocular/releases/download/1.5.2/ocular.phar
        php${{matrix.php}} ocular.phar code-coverage:upload --format=php-clover /tmp/clover.xml
        php${{matrix.php}} vendor/bin/php-coveralls -v
      env:
        COVERALLS_RUN_LOCALLY: 1
        COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: CODING_STANDARD
      if: matrix.php == 7.1
      run: |
        composer install --prefer-dist
        ./vendor/bin/phpcs
    - name: STATIC_ANALYSIS
      if: matrix.php == 7.1
      run: |
        composer install --prefer-dist
        ./vendor/bin/phpcs
