name: CI

on:
  push:
    branches:
    tags:
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
        operating-system: [ubuntu-18.04]
        env: ['EXECUTOR= DEPENDENCIES=--prefer-lowest', 'EXECUTOR=coroutine DEPENDENCIES=--prefer-lowest', 'EXECUTOR=', 'EXECUTOR=coroutine']
        include:
          - os: ubuntu-18.04
            php: 7.1
            env: EXECUTOR=coroutine
    steps:
    - uses: actions/checkout@v1
    - name: Install PHP
      uses: shivammathur/setup-php@1.5.2
      with:
        php-version: ${{ matrix.php  }}
        extension-csv: dom, mbstring
        coverage: xdebug
    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install dependencies
      run: |
        export $ENV
        composer update ${DEPENDENCIES}
      env:
        ENV: ${{ matrix.env }}
    - name: Run unit tests
      run: |
        export $ENV
        ./vendor/bin/phpunit --group default,ReactPromise
      env:
        ENV: ${{ matrix.env}}
    - name: Code coverage
      if: matrix.php == 7.1 && matrix.env == 'EXECUTOR=coroutine'
      run: |
        export $ENV
        ./vendor/bin/phpunit --coverage-php /tmp/coverage/clover_executor.cov
        ./vendor/bin/phpunit --coverage-php /tmp/coverage/clover_executor-coroutine.cov
        ./vendor/bin/phpcov merge /tmp/coverage --clover /tmp/clover.xml
        wget https://github.com/scrutinizer-ci/ocular/releases/download/1.5.2/ocular.phar
        php${{matrix.php}} ocular.phar code-coverage:upload --format=php-clover /tmp/clover.xml
      env:
        ENV: ${{ matrix.env }}
    - name: Coding Standard
      if: matrix.php == 7.1
      run: |
        composer update --prefer-dist
        composer lint
    - name: PHPStan
      if: matrix.php == 7.1
      run: |
        composer update --prefer-dist
        composer stan
